#!/usr/bin/with-contenv bash
echo "-----------------------------------------------------------------------------"
echo " |~) _ ._  _| _ ._ _ |\ |o._  o _ |~|_|_|"
echo " |~\(_|| |(_|(_)| | || \||| |_|(_||~| | |<"
echo " Presents: radarr-extended"
echo " Docker Version: $dockerVersion"
echo " May the vidz be with you!"
echo "-----------------------------------------------------------------------------"
echo "Donate: https://github.com/sponsors/RandomNinjaAtk"
echo "Project: https://github.com/RandomNinjaAtk/docker-radarr-extended"
echo "Support: https://github.com/RandomNinjaAtk/docker-radarr-extended/discussions"
echo "-----------------------------------------------------------------------------"

if [ "$enableRecyclarr" != "true" ]; then
	echo "Recyclarr disabled, enable by setting parameter: enableRecyclarr=true"
	exit
fi

echo "Starting Script...."
for (( ; ; )); do
	let i++
	if [ ! -d "/config/logs" ]; then
		mkdir -p "/config/logs" 
		chmod 777 "/config/logs" 
		chown abc:abc "/config/logs" 
	fi
	if [ -f "/config/extended/logs/log-cleanup" ]; then
		rm "/config/extended/logs/log-cleanup"
	fi
	touch -d "24 hours ago" "/config/extended/logs/log-cleanup"
	if find "/config/logs" -type f -iname "extended_recyclarr_*.txt" -not -newer "/config/extended/logs/log-cleanup" | read; then
		find "/config/logs" -type f -iname "extended_recyclarr_*.txt" -not -newer "/config/extended/logs/log-cleanup" -delete
	fi
	if [ -f "/config/extended/logs/log-cleanup" ]; then
		rm "/config/extended/logs/log-cleanup"
	fi
	bash /config/extended/scripts/recyclarr.sh 2>&1 | tee "/config/logs/extended_recyclarr_${i}_$(date +"%Y_%m_%d_%I_%M_%p").txt" > /proc/1/fd/1 2>/proc/1/fd/2
	if [ -z "$scriptInterval" ]; then
		scriptInterval="4h"
	fi
	echo "Script sleeping for $scriptInterval..."
	sleep $scriptInterval
done


exit $?
