#!/usr/bin/with-contenv bash
if [ "$enableRecyclarr" != "true" ]; then
	echo "Recyclarr disabled, enable by setting parameter: enableRecyclarr=true"
	sleep infinity
else
	echo "Waiting for Radarr to startup..."
	sleep 2m
fi

echo "Starting Script...."
for (( ; ; )); do
	let i++
	bash /config/extended/scripts/Recyclarr.bash
	echo "Script sleeping for 4 hours..."
	sleep 4h
done


exit $?
